/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef parameter_server_CONSTANTS_H
#define parameter_server_CONSTANTS_H

#include "parameter_server_types.h"



class parameter_serverConstants {
 public:
  parameter_serverConstants();

};

extern const parameter_serverConstants g_parameter_server_constants;



#endif
