// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "ParameterServer.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

class ParameterServerHandler : virtual public ParameterServerIf {
 public:
  ParameterServerHandler() {
    // Your initialization goes here
  }

  void pull(std::string& _return, const int32_t epoch) {
    // Your implementation goes here
    printf("pull\n");
  }

  void push(const int32_t epoch, const std::string& gradient) {
    // Your implementation goes here
    printf("push\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<ParameterServerHandler> handler(new ParameterServerHandler());
  ::std::shared_ptr<TProcessor> processor(new ParameterServerProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

