/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "parameter_server_constants.h"



const parameter_serverConstants g_parameter_server_constants;

parameter_serverConstants::parameter_serverConstants() {
}



