/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef task_CONSTANTS_H
#define task_CONSTANTS_H

#include "task_types.h"



class taskConstants {
 public:
  taskConstants();

};

extern const taskConstants g_task_constants;



#endif
