# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parameter_server.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='parameter_server.proto',
  package='task',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x16parameter_server.proto\x12\x04task\":\n\x15ParametersOrGradients\x12!\n\x05pairs\x18\x01 \x03(\x0b\x32\x12.task.KeyValuePair\"H\n\x0cKeyValuePair\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x64im\x18\x02 \x01(\r\x12\r\n\x05shape\x18\x03 \x03(\r\x12\x0e\n\x06values\x18\x04 \x03(\x02'
)




_PARAMETERSORGRADIENTS = _descriptor.Descriptor(
  name='ParametersOrGradients',
  full_name='task.ParametersOrGradients',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pairs', full_name='task.ParametersOrGradients.pairs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=90,
)


_KEYVALUEPAIR = _descriptor.Descriptor(
  name='KeyValuePair',
  full_name='task.KeyValuePair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='task.KeyValuePair.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dim', full_name='task.KeyValuePair.dim', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shape', full_name='task.KeyValuePair.shape', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='task.KeyValuePair.values', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=164,
)

_PARAMETERSORGRADIENTS.fields_by_name['pairs'].message_type = _KEYVALUEPAIR
DESCRIPTOR.message_types_by_name['ParametersOrGradients'] = _PARAMETERSORGRADIENTS
DESCRIPTOR.message_types_by_name['KeyValuePair'] = _KEYVALUEPAIR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ParametersOrGradients = _reflection.GeneratedProtocolMessageType('ParametersOrGradients', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETERSORGRADIENTS,
  '__module__' : 'parameter_server_pb2'
  # @@protoc_insertion_point(class_scope:task.ParametersOrGradients)
  })
_sym_db.RegisterMessage(ParametersOrGradients)

KeyValuePair = _reflection.GeneratedProtocolMessageType('KeyValuePair', (_message.Message,), {
  'DESCRIPTOR' : _KEYVALUEPAIR,
  '__module__' : 'parameter_server_pb2'
  # @@protoc_insertion_point(class_scope:task.KeyValuePair)
  })
_sym_db.RegisterMessage(KeyValuePair)


# @@protoc_insertion_point(module_scope)
